//Sessions
export const FETCH_SESSION = 'FETCH_SESSION';
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE';

export const FETCH_CLOSE_SESSION = 'FETCH_CLOSE_SESSION';
export const UPDATE_NAME_SESSION = 'UPDATE_NAME_SESSION';
